services:
  dev:
    build:
      context: ./.devcontainer
      dockerfile: Dockerfile
    ports:
      - "1455:1455"
    init: true
    volumes:
      - ./:/usr/src/app # ローカルをコンテナ内にマウント
      - ./.codex/:/home/node/.codex
    command: sleep infinity
