services:
  dev:
    build:
      context: ./.devcontainer
      dockerfile: Dockerfile
    ports:
      - "1455:1455"
    volumes:
      - ./:/usr/src/app # ローカルをコンテナ内にマウント
    command: sleep infinity
